export const PERMISSIONS = [
  "identity.users.read",
  "identity.users.invite",
  "identity.users.disable",
  "identity.roles.read",
  "identity.roles.write",
  "identity.audit.read",
  "organization.settings.read",
  "organization.settings.write",
  "organization.branches.write",
  "organization.fiscal.write",
  "hr.employees.read",
  "hr.employees.write",
  "hr.attendance.write",
  "hr.leave.approve",
  "hr.payroll.run",
  "hr.payroll.post",
  "inventory.products.read",
  "inventory.products.write",
  "inventory.warehouses.write",
  "inventory.stock.read",
  "inventory.stock.adjust",
  "inventory.stock.transfer",
  "sales.customers.read",
  "sales.customers.write",
  "sales.quotations.write",
  "sales.orders.confirm",
  "sales.invoices.post",
  "sales.payments.post",
  "sales.returns.post",
  "purchase.suppliers.write",
  "purchase.requisitions.approve",
  "purchase.orders.approve",
  "purchase.grn.post",
  "purchase.invoices.post",
  "finance.accounts.write",
  "finance.journals.post",
  "finance.journals.reverse",
  "finance.periods.close",
  "finance.reports.read",
  "crm.leads.write",
  "crm.opportunities.write",
  "reports.dashboards.read",
  "reports.export",
] as const;

export type PermissionCode = (typeof PERMISSIONS)[number];
